# Generated by Django 4.1.5 on 2023-01-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_name', models.CharField(max_length=250)),
                ('cake_desc', models.TextField()),
                ('cake_price', models.IntegerField()),
            ],
        ),
    ]
