# Generated by Django 4.1.5 on 2023-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='cake_img',
            field=models.ImageField(default='cakesbipin', upload_to='cake-imges'),
            preserve_default=False,
        ),
    ]
