# Generated by Django 4.1.5 on 2023-01-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0002_cake_cake_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='cake_flavour',
            field=models.CharField(default='bipin', max_length=250),
            preserve_default=False,
        ),
    ]
